name: Xolentum GUI Wallet Build

on:
  push:
    branches:
      - master
      - development
  pull_request:
    branches:
      - development 

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v1

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: "12.18.3"
      
      - name: Install quasar
        run: npm install -g @quasar/cli      
      
      - name: Install dependencies
        run: npm install

      - name: Download xolentumd binaries
        run: node ./build/download-binaries.js
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract binaries
        run: unzip latest.zip
        shell: bash
        working-directory: ./downloads

      - name: Move xolentumd binaries
        run: |
          find ./downloads -type f -name "xolentumd*" -exec cp '{}' ./bin \;
          find ./downloads -type f -name "xolentum-wallet-rpc*" -exec cp '{}' ./bin \;
        shell: bash

      - name: Verify binaries
        run: ls ./bin
        shell: bash

      - name: Publish Window and Linux binaries
        if: runner.os != 'macOS'
        run: npm run build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Mac binaries
        if: runner.os == 'macOS'
        run: npm run build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_LINK: ${{ secrets.MAC_CERTIFICATE }}
          CSC_KEY_PASSWORD: ${{ secrets.MAC_CERTIFICATE_PASSWORD }}
          SIGNING_APPLE_ID: ${{ secrets.SIGNING_APPLE_ID }}
          SIGNING_APP_PASSWORD: ${{ secrets.SIGNING_APP_PASSWORD }}
          SIGNING_TEAM_ID: ${{ secrets.SIGNING_TEAM_ID }}

      - name: Remove un-needed artifacts
        run: rm -r -- ./*/
        shell: bash
        working-directory: ./dist/electron-mat/Packaged

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: ${{ runner.OS }}
          path: dist/electron-mat/Packaged
